---
- name: "create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Copy Backend file"
  copy:
    src:  /home/circleci/project/artifact.tar.gz
    dest: ~/backend-app

- name: "unarchive backend files"
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: ~/backend-app

# - name: "installing npm"
#   become: true
#   apt:
#     name: ["npm"]
#     state: latest
#     update_cache: yes 

- name: "install node dep"
  shell: |
    cd ~/backend-app
    npm install

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present
    
- name: "executing node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start npm -- start

- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
