---
# - name: "create backend app directory"
#   file:
#     path: /home/ubuntu/backend-app
#     state: directory

- name: "Copy Backend file"
  copy:
    src:  artifact.tar.gz
    dest: /home/ubuntu 

- name: "unarchive backend files" 
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu

- name: "install node dep"
  shell: |
    cd /home/ubuntu/backend 
    npm install

- name: "executing node app with PM2"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js

- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
    
